### PR TITLE
Convert to Dist-Zilla.

### PR DESCRIPTION
**Pull request by shlomif**
This is done as part of the pull-request challenge. Module-Install is undermaintained and unloved.

### CODE REVIEW

**Comment by shlomif** [comment]
Hi all! Why wasn't this pull-request merged (or at least dismissed with a useful comment yet)? Ping!

**Comment by sni** [comment]
I don't see the advantage to add Dist-Zilla as new (build) dependency. Module-Install just works and does everything we need.

**Comment by shlomif** [comment]
@sni: hi! Sorry for the late reply. Some of the advantages of Dist-Zilla over Module-Install:

1. Ability to generate a META.json file.

2. Module-Install has become abandoned and unmaintained.

3. Module-Install will break with upcoming perl 5's that will remove `.` from the installation path by default.

4. Module-Install plugins are hard to figure out and install.

5. Dist-Zilla is not required to install the distribution from CPAN, just to build from the VM.

**Comment by sni** [comment]
I just tried to this PR.

1. It fails to build the module:
```
[DZ] beginning to build Monitoring-Plugin
[DZ] guessing dist's main_module is lib/Monitoring/Plugin.pm
[@Filter/ExtraTests] rewriting author test xt/author/pod-syntax.t
[RewriteVersion] Skipping: no "our $VERSION = '...'" found in "lib/Monitoring/Plugin/Config.pm"
[RewriteVersion] Skipping: no "our $VERSION = '...'" found in "lib/Monitoring/Plugin/ExitResult.pm"
[RewriteVersion] Skipping: no "our $VERSION = '...'" found in "lib/Monitoring/Plugin/Getopt.pm"
[RewriteVersion] Skipping: no "our $VERSION = '...'" found in "lib/Monitoring/Plugin/Performance.pm"
[RewriteVersion] Skipping: no "our $VERSION = '...'" found in "lib/Monitoring/Plugin/Range.pm"
[RewriteVersion] Skipping: no "our $VERSION = '...'" found in "lib/Monitoring/Plugin/Threshold.pm"
[DZ] attempt to add META.yml multiple times; added by: filename set by GatherDir (Dist::Zilla::Plugin::GatherDir line 225); encoded_content added by @Filter/GatherDir (Dist::Zilla::Plugin::GatherDir line 226); text from coderef added by @Filter/MetaYAML (Dist::Zilla::Plugin::MetaYAML line 70)
aborting; duplicate files would be produced at /home/sven/perl5/lib/perl5/Dist/Zilla/App/Command/build.pm line 75.
```

2. The tests also fail.

3. I am a bit worried about pulling in a new dependency which itself has so many depencencies. It even requires Moose just to build a module.

But so far i don't see any advantage besides being more modern.

**Pull request closed without merging**
